// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240928212025_AddJson")]
    partial class AddJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.BasicVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MlId")
                        .HasColumnType("text")
                        .HasColumnName("ml_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("WebApi.Models.BasicVideo", b =>
                {
                    b.OwnsMany("WebApi.Models.Highlight", "Highlights", b1 =>
                        {
                            b1.Property<Guid>("BasicVideoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("End")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "end");

                            b1.Property<string>("File")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "file");

                            b1.Property<int>("Start")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "start");

                            b1.Property<int>("Virality")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "virality");

                            b1.HasKey("BasicVideoId", "Id");

                            b1.ToTable("videos");

                            b1.ToJson("highlights");

                            b1.WithOwner()
                                .HasForeignKey("BasicVideoId")
                                .HasConstraintName("fk_videos_videos_basic_video_id");
                        });

                    b.Navigation("Highlights");
                });
#pragma warning restore 612, 618
        }
    }
}
